<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsRolesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions_roles')->insert([
           [
               'permissions_id'=>1,
               'roles_id'=>1
           ],
            [
                'permissions_id'=>2,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>3,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>4,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>5,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>6,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>7,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>8,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>9,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>10,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>11,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>12,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>13,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>14,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>15,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>16,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>17,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>18,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>19,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>20,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>21,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>22,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>23,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>24,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>25,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>26,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>27,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>28,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>29,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>30,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>31,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>32,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>33,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>34,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>35,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>36,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>37,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>38,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>39,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>40,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>41,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>42,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>43,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>44,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>45,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>46,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>47,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>48,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>49,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>50,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>51,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>52,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>53,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>54,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>55,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>56,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>57,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>58,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>59,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>60,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>61,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>62,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>63,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>64,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>65,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>66,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>67,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>68,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>69,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>70,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>71,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>72,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>73,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>74,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>75,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>76,
                'roles_id'=>1
            ],
            [
                'permissions_id'=>77,
                'roles_id'=>1
            ]
        ]);
        //
    }
}
